# Generated by Django 6.0.5 on 2026-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='titleName',
            field=models.CharField(default='""', max_length=200),
            preserve_default=False,
        ),
    ]
