# Generated by Django 6.0.5 on 2026-05-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_titlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='titleName',
            new_name='title',
        ),
    ]
